### ISSUE TITLE
Auto apprentissage des coef

### ISSUE THREAD

**Issue by AntorFr** [AntorFr/SmartVT#1]
Ajouter un auto apprentissage des coefficients de chauffe.

**Comment by ptibubu** [comment]
Est ce qu'il est possible de savoir comment sont calculés ces coefs? En particulier, d'où vient la formule du constT ?

Merci

**Comment by AntorFr** [comment]
Les coefs sont calculés calibré automatiquement en fonction des cycles de chauffe précédents

**Comment by ptibubu** [comment]
Merci pour la réponse, mais j'aimerais comprendre la formule/l'équation thermodynamique derriere l'auto callibration pour pouvoir adapter un TPI sur d'autres plateformes.

Autant je comprends l'update du constC (puissance radiateur constante, variation linéaire de la température avec le temps), mais je ne vois pas d'où sort la formule du consT.
A priori, je dirais que la la variation de la température est prop à la différence de température, donc variation exponentielle de la température en fonction du temps, non? Mais après ... ?!

Est qu'il y aurait une référence, ou une explication au calcul de ce constT ?
Merci!
